### ISSUE TITLE
master: Analyzing log fails

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp-module-statistics#8]
```
[saml@webapp-10 scripts]$ ./analyze_logs.sh
Statistics directory   : /apps/statistics_out/instance/
Input file             : /var/cache/simplesamlphp/statistics/instance.log
Offset                 : 3600
Memory usage           : 1.74 MB
Memory usage           : 2.02 MB
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to SimpleSAML\Module\statistics\DateHandlerMonth::fromSlot() must be of the type int, null given, called in /apps/installation/simplesamlphp/simplesamlphp-master/modules/statistics/lib/Aggregator.php on line 336 and defined in /apps/installation/simplesamlphp/simplesamlphp-master/modules/statistics/lib/DateHandlerMonth.php:40
Stack trace:
#0 /apps/installation/simplesamlphp/simplesamlphp-master/modules/statistics/lib/Aggregator.php(336): SimpleSAML\Module\statistics\DateHandlerMonth->fromSlot()
#1 /apps/installation/simplesamlphp/simplesamlphp-master/modules/statistics/bin/loganalyzer.php(62): SimpleSAML\Module\statistics\Aggregator->store()
#2 {main}
  thrown in /apps/installation/simplesamlphp/simplesamlphp-master/modules/statistics/lib/DateHandlerMonth.php on line 40
```

**Comment by tvdijen** [comment]
Closed in 72b49b786da0410c6637269e93c86b13216be149
